name: Deploy Files via FTP (Production)

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  ftp-deploy:
    name: "Deploy via FTP"
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "FTP Deploy"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "198.175.25.37"
          username: "studentloanplannercom"
          password: ${{ secrets.FTP_PASSWORD_PRD }}
          local-dir: "./" # Set to the local directory you want to deploy
          server-dir: "/public/wp-content/themes/student-loan-planner-theme/" # Update with your server path
