name: Deploy Files via FTP

on:
  push:
    branches:
      - stage
    paths:
      - '**' # Trigger for any change in any file
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

jobs:
  ftp-deploy:
    name: "Deploy via FTP"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "FTP Deploy"
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "198.175.25.37"
          username: "studentloanplannercombigscoots-stagingcom"
          password: "*H\*`bo{X\H5n,JR{sb4V?zf@u5"
          local-dir: "./" # Set to the local directory you want to deploy
          server-dir: "/public/wp-content/themes/student-loan-planner-theme/" # Update with your server path
