name: Deploy to WP Engine
on:
  push:
    branches:
     - stage
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: GitHub Action Deploy to WP Engine
      uses: wpengine/github-action-wpe-site-deploy@v3.0
      with:
        # Deploy vars
        WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPE_SSHG_KEY_PRIVATE }} 
        WPE_ENV: studentloanplanner
        # Deploy Options
        REMOTE_PATH: "wp-content/themes/student-loan-planner-theme"
        PHP_LINT: FALSE
        CACHE_CLEAR: TRUE
